import { markdownResponse } from "@/lib/agent-markdown";
import type { WorkerEnv } from "@/lib/env";
import { originFor } from "@/lib/origins";
import { jsonResponse } from "@/lib/responses";

export const API_CATALOG_CONTENT_TYPE =
  "application/linkset+json; charset=utf-8";
export const OPENAPI_JSON_CONTENT_TYPE =
  "application/openapi+json; charset=utf-8";
export const OPENAPI_YAML_CONTENT_TYPE = "application/yaml; charset=utf-8";

export function buildApiCatalog(appOrigin: string, siteOrigin: string) {
  return {
    linkset: [
      {
        anchor: `${appOrigin}/api`,
        "service-desc": [
          {
            href: `${siteOrigin}/openapi.json`,
            type: "application/openapi+json",
          },
          {
            href: `${siteOrigin}/openapi.yaml`,
            type: "application/yaml",
          },
        ],
        "service-doc": [
          {
            href: `${siteOrigin}/llms.txt`,
          },
        ],
        status: [
          {
            href: `${appOrigin}/api/health`,
          },
        ],
        describedby: [
          {
            href: `${siteOrigin}/auth.md`,
          },
        ],
      },
    ],
  };
}

export function buildAgentCard(appOrigin: string, siteOrigin: string) {
  return {
    name: "coeditHTML",
    version: "1.0.0",
    description:
      "Real-time collaborative editing, sticky redlining, and instant sharing for single-file HTML artifacts generated by AI tools.",
    protocolVersion: "1.0",
    url: siteOrigin,
    documentationUrl: `${siteOrigin}/llms.txt`,
    provider: {
      name: "coeditHTML",
      url: siteOrigin,
    },
    supportedInterfaces: [
      {
        url: `${appOrigin}/api`,
        protocolBinding: "HTTP+JSON",
        protocolVersion: "1.0",
      },
    ],
    capabilities: {
      streaming: true,
      pushNotifications: false,
    },
    skills: [
      {
        id: "publish_artifact",
        name: "Publish Artifact",
        description:
          "Upload a standalone single-file HTML artifact (up to 5MB) and instantly generate distinct view, suggest, and edit share URLs.",
        tags: ["html", "publishing", "collaboration", "upload"],
      },
      {
        id: "get_artifact",
        name: "Get Artifact Metadata",
        description:
          "Fetch metadata, capabilities (canWrite, canSuggest), and settings for an artifact using its share token.",
        tags: ["metadata", "permissions"],
      },
      {
        id: "replace_artifact",
        name: "Replace Artifact Revision",
        description:
          "Upload a new revision of the HTML artifact using an edit-capable token.",
        tags: ["revision", "update"],
      },
      {
        id: "download_artifact",
        name: "Download Artifact",
        description:
          "Download the raw original HTML or the artifact with edited text and embedded feedback stickies.",
        tags: ["export", "download"],
      },
      {
        id: "manage_settings",
        name: "Manage Artifact Settings",
        description:
          "Configure or remove passwords and update permissions for an artifact using an edit token.",
        tags: ["security", "password", "settings"],
      },
    ],
  };
}

export const AUTH_MD_DOCUMENT = `# coeditHTML auth.md

Guide for autonomous AI agents, orchestrators, and automated clients interacting with coeditHTML.

## Overview

coeditHTML provides instant hosting and real-time collaboration for single-file HTML artifacts generated by AI tools.

- **No account or pre-registration required**: Agents can upload and publish artifacts immediately without API keys.
- **Token-based authorization**: Each published artifact produces three distinct, unguessable capability tokens:
  - \`viewToken\`: Read-only access to view the artifact.
  - \`suggestToken\`: Permission to add sticky comments and suggestions.
  - \`editToken\`: Permission to edit text in place, upload revisions, configure passwords, and manage share links.

## Agent Registration & Upload Endpoint

Upload standalone HTML via \`POST /api/artifacts\`:

\`\`\`http
POST https://app.coedithtml.com/api/artifacts
Content-Type: multipart/form-data
\`\`\`

Form field \`file\`: raw HTML document (max 5MB).
Optional fields: \`password\`, \`draft\`.

## Response
\`\`\`json
{
  "artifactId": "art_01j9x...",
  "viewUrl": "https://app.coedithtml.com/s/v_abc...",
  "suggestUrl": "https://app.coedithtml.com/s/s_def...",
  "editUrl": "https://app.coedithtml.com/s/e_ghi...",
  "published": true
}
\`\`\`
`;

export const APP_HOME_MARKDOWN = `# coeditHTML App

Instant hosting and real-time collaboration for single-file HTML artifacts.

## Quickstart for Agents

Upload any self-contained HTML file to create a live shareable workspace:

\`\`\`bash
curl -X POST "https://app.coedithtml.com/api/artifacts" \\
  -F "file=@./report.html"
\`\`\`

## Key Endpoints

- \`POST /api/artifacts\`: Upload and publish a new HTML artifact.
- \`GET /api/artifacts/{token}\`: Inspect metadata, permissions, and view URLs.
- \`POST /api/artifacts/{token}/revisions\`: Upload a revised HTML version.
- \`GET /tutorial\`: Launch interactive guided tutorial session.
- \`GET /.well-known/api-catalog\`: Machine-readable API index (RFC 9727).
- \`GET /.well-known/agent-card.json\`: Agent-to-Agent discovery manifest.
- \`GET /auth.md\`: Agent registration and authorization documentation.
- \`GET /openapi.json\`: OpenAPI 3.1.0 specification.
`;

export const TUTORIAL_MARKDOWN = `# coeditHTML Interactive Tutorial

coeditHTML lets non-technical stakeholders review, redline, and edit HTML artifacts directly in the browser.

## Features Covered

1. **Sticky Notes**: Click anywhere on the artifact to pin a comment or feedback thread.
2. **In-Place Text Editing**: Click directly on headings and paragraphs to edit copy with instant preview.
3. **Share Links**: Granular \`view\`, \`suggest\`, and \`edit\` access levels.
4. **Revisions & Export**: Download the clean HTML or an edited version with changes baked in.

To start an interactive browser session, visit \`/tutorial\` in a web browser.
`;

export function handleApiCatalog(request: Request, env: WorkerEnv): Response {
  const appOrigin = originFor(request, env.APP_HOST);
  const siteOrigin = "https://coedithtml.com";
  const catalog = buildApiCatalog(appOrigin, siteOrigin);
  return new Response(JSON.stringify(catalog, null, 2), {
    headers: {
      "content-type": API_CATALOG_CONTENT_TYPE,
      "access-control-allow-origin": "*",
    },
  });
}

export function handleAgentCard(request: Request, env: WorkerEnv): Response {
  const appOrigin = originFor(request, env.APP_HOST);
  const siteOrigin = "https://coedithtml.com";
  const card = buildAgentCard(appOrigin, siteOrigin);
  return jsonResponse(card, 200, {
    "access-control-allow-origin": "*",
  });
}

export function handleAuthMd(): Response {
  return markdownResponse(AUTH_MD_DOCUMENT, 200, {
    "access-control-allow-origin": "*",
  });
}

export function handleHealth(): Response {
  return jsonResponse(
    {
      status: "ok",
      service: "coedit-worker",
    },
    200,
    {
      "access-control-allow-origin": "*",
    },
  );
}

export function handleAppHomeMarkdown(): Response {
  return markdownResponse(APP_HOME_MARKDOWN);
}

export function handleTutorialMarkdown(): Response {
  return markdownResponse(TUTORIAL_MARKDOWN);
}
