import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/build/**",
      // Staged copy of the app and runtime builds, assembled before deploy.
      "worker/public/**",
      "**/.next/**",
      "**/.wrangler/**",
      "**/node_modules/**",
      // Next-managed file; regenerated on every build, never hand-edited.
      "website/next-env.d.ts",
      // Generated by `wrangler types` from wrangler.jsonc.
      "worker/worker-configuration.d.ts",
    ],
  },
  js.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    extends: [...tseslint.configs.strict],
    rules: {
      // TypeScript itself catches undefined references more accurately.
      "no-undef": "off",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-imports": "error",
    },
  },
  {
    files: ["**/*.{js,mjs,cjs}"],
    languageOptions: {
      globals: globals.node,
    },
  },
);
