export {
  DEFAULT_MARK_COLOR,
  MARK_COLORS,
  MARK_EDGE,
  MARK_FILL,
  OVERLAY_VERSION,
  ROOM_VERSION,
  UNLOCK_QUERY_PARAM,
  addEntryMessage,
  helloMessage,
  parseRoomToClientMessage,
  parseRuntimeToAppMessage,
  patchEntryMessage,
  removeEntryMessage,
  renderMarksMessage,
  repliesTo,
  setToolMessage,
  type Anchor,
  type AppToRuntimeMessage,
  type Author,
  type ClientToRoomMessage,
  type CommentEntry,
  type EntryPatch,
  type EntryStatus,
  type FitMode,
  type MarkColor,
  type OverlayEntry,
  type ReaderPresence,
  type RejectionReason,
  type ReplyEntry,
  type RoomToClientMessage,
  type RuntimeToAppMessage,
  type StickyEntry,
  type TextAnchor,
  type ViewportRect,
} from "@coedithtml/protocol";
