export const TREE_NAMES: readonly string[] = [
  "Alder",
  "Applewood",
  "Arbutus",
  "Ash",
  "Aspen",
  "Balsam Fir",
  "Bamboo",
  "Banyan",
  "Baobab",
  "Bay Laurel",
  "Beech",
  "Birch",
  "Black Walnut",
  "Blue Spruce",
  "Bonsai",
  "Boxwood",
  "Bristlecone",
  "Buckeye",
  "Catalpa",
  "Cedar",
  "Cherry Blossom",
  "Chestnut",
  "Chinquapin",
  "Clover",
  "Coral Bark",
  "Cottonwood",
  "Crepe Myrtle",
  "Cypress",
  "Dogwood",
  "Douglas Fir",
  "Ebony",
  "Elderberry",
  "Elm",
  "Eucalyptus",
  "Fern",
  "Fig",
  "Fraser Fir",
  "Ginkgo",
  "Hawthorn",
  "Hazel",
  "Hemlock",
  "Hickory",
  "Holly",
  "Hornbeam",
  "Ironwood",
  "Ivy",
  "Jacaranda",
  "Joshua Tree",
  "Juniper",
  "Kapok",
  "Larch",
  "Laurel",
  "Lichen",
  "Linden",
  "Live Oak",
  "Madrone",
  "Magnolia",
  "Mahogany",
  "Manzanita",
  "Maple",
  "Mesquite",
  "Mimosa",
  "Monkey Puzzle",
  "Moss",
  "Mountain Ash",
  "Myrtle",
  "Oak",
  "Olive",
  "Osage Orange",
  "Palm",
  "Palmetto",
  "Pecan",
  "Persimmon",
  "Pine",
  "Pitch Pine",
  "Ponderosa",
  "Poplar",
  "Redbud",
  "Red Maple",
  "Redwood",
  "Rowan",
  "Sage",
  "Sassafras",
  "Sequoia",
  "Serviceberry",
  "Silverbell",
  "Silver Birch",
  "Slash Pine",
  "Sourwood",
  "Spruce",
  "Sugar Maple",
  "Sugar Pine",
  "Sumac",
  "Sweetgum",
  "Sycamore",
  "Tamarack",
  "Teak",
  "Tupelo",
  "Viburnum",
  "Weeping Willow",
  "White Pine",
  "Willow",
  "Witch Hazel",
  "Yew",
  "Zelkova",
];

export function randomTreeName(seed?: string): string {
  if (seed) {
    let hash = 0;
    for (const char of seed) {
      hash = (hash * 31 + char.charCodeAt(0)) % 4294967296;
    }
    return TREE_NAMES[Math.abs(hash) % TREE_NAMES.length] ?? "Willow";
  }
  const index = Math.floor(Math.random() * TREE_NAMES.length);
  return TREE_NAMES[index] ?? "Willow";
}
